[package]
name = "canoon"
version = "0.1.0"
edition = "2021"

[dependencies]
is-root = "0.1.3"
dialoguer = "0.11.0"

[profile.release]
opt-level = 3
lto = true
panic = "abort"
codegen-units = 1
strip = true
